---
- name: Install NVM dependencies
  apt:
    pkg={{ item }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  with_items:
    - git
    - curl
    - build-essential
    - libssl-dev
  become:
    yes
  tags: 
    nodejs

- name: Install NVM
  git:
    repo=https://github.com/creationix/nvm.git
    dest={{ role_nodejs_nvm_destination }}
    version={{ role_nodejs_nvm_version }}
  become:
    yes
  become_user:
    "{{ role_nodejs_nvm_user }}"
  tags:
    nodejs

- name: Sourcing NVM in ~/.profile
  lineinfile:
    dest=~/.profile
    line="source {{ role_nodejs_nvm_destination }}/nvm.sh"
    create=yes
  become:
    yes
  become_user:
    "{{ role_nodejs_nvm_user }}"
  tags: 
    nodejs

- name: Install {{ role_nodejs_version }}
  command: 
    sudo -iu {{ role_nodejs_nvm_user }} nvm install {{ role_nodejs_version }}
  register: 
    nvm_install_result
  changed_when: 
    "'v{{ role_nodejs_version }} is already installed.' not in nvm_install_result.stderr"
  tags: 
    nodejs

- name: Check if {{ role_nodejs_version }} is the default node version
  shell: 
    sudo -iu {{ role_nodejs_nvm_user }} nvm ls | grep -e 'default -> {{ role_nodejs_version }}'
  register: 
    nvm_check_default
  changed_when:
    nvm_check_default.rc == 1
  failed_when:
    False
  tags: 
    nodejs

- name: Set default node version to {{ role_nodejs_version }}
  command: 
    sudo -iu {{ role_nodejs_nvm_user }} nvm alias default {{ role_nodejs_version }}
  when:
    nvm_check_default.rc == 1
  tags: 
    nodejs
